### PR TITLE
Add s390x build support + documentation

### PR DESCRIPTION
**Pull request by sriemer**
See https://github.com/sriemer/instana-agent-static-docker/blob/s390x/README_s390x.md how this works.

### CODE REVIEW

**Review by discount-elf — COMMENTED** [review]
This looks good with the following exception:

- We should fetch a numbered release of gomplate and validate a sha256 digest

**Comment by sriemer** [comment]
Thanks for the feedback. Will amend accordingly.

**Comment by sriemer** [comment]
Review comments have been addressed. One more commit has been added.

**Comment by discount-elf** [comment]
Perfect. Looks good!

**Pull request merged**
